feat(twitter): hide views on timeline
ReVanced/revanced-patches-template pull request #1371
Opened 2022-12-26 22:16 UTC by Franckyi

This new patch partly fixes #1356 by removing the views stat on the timeline.
I had planned to remove the views stat when opening a tweet as well, but I couldn't get it to work without crashing (seemed like I couldn't just remove the element in the view like I did here because it was referenced somewhere in the code, resulting in an Exception).
I tested the patch on app version 9.69.1 and it works fine.
Also this is my first contribution here so I'm open to any suggestions.

2022-12-26 22:38 UTC, Franckyi commented
Marking it as draft as I am not entirely happy with how the icons are aligned (see the margin on the right due to one of the elements being removed). I wanna figure out how to make them evenly spaced.

![image](https://user-images.githubusercontent.com/17572738/209586758-789958a1-6a0a-4fda-84b6-449591494f27.png)

2022-12-28 20:34 UTC, Franckyi commented
I fixed the issue I had by making a bytecode patch instead of a resource patch. I also managed to remove the view count under a tweet when you open it (it now fully matches the request #1356).
As this is the first time I'm contributing here and had no prior experience with fingerprinting, I'd like to know if everything seems right. I tested it on version 9.69.1 again and it seems to be working fine.

2022-12-28 20:39 UTC, oSumAtrIX requested changes
Looks good, you can reduce duplicate code by creating a function which takes a transformer and the fingerprint it works with as parameters. Then you can get rid of the duplicate code of getting the result of the fingerprints each time.

2022-12-28 20:39 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/fingerprints/TweetStatsContainerConstructorFingerprint.kt
> +    parameters = listOf("Landroid/view/View;"),
For parameter types only the prefixing char is checked:

```suggestion
    parameters = listOf("L"),
```

2022-12-28 20:39 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/fingerprints/TweetStatsContainerWrapperConstructorFingerprint.kt
> +    parameters = listOf("Landroid/widget/RelativeLayout;"),
```suggestion
    parameters = listOf("L;"),
```

2022-12-29 02:09 UTC, oSumAtrIX approved these changes

2022-12-29 02:09 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/patch/HideViewsResourcePatch.kt
> +@Name("hide-views")
```suggestion
@Name("hide-views-stats")
```

2022-12-29 02:10 UTC, merged

2022-12-29 02:10 UTC, oSumAtrIX commented
Thanks!