feat(Photomath): Add unlock plus version patch
ReVanced/revanced-patches-template pull request #1633
Opened 2023-02-16 18:37 UTC by nik2143

Unlock features of photomath plus
Closes #1461

2023-02-17 16:41 UTC, oSumAtrIX requested changes

2023-02-17 16:41 UTC, oSumAtrIX commented on CHANGELOG.md
> +# [2.162.0](https://github.com/revanced/revanced-patches/compare/v2.161.1...v2.162.0) (2023-02-14)
This file is autogenerated, do not commit it.

2023-02-17 16:41 UTC, oSumAtrIX commented on gradle.properties
> +version = 2.162.0
This file is autogenerated, do not commit it.

2023-02-17 16:41 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/fingerprints/MainOnCreateingerprint.kt
> +object MainOnCreateingerprint : MethodFingerprint(
```suggestion
object MainOnCreateFingerprint : MethodFingerprint(
```

2023-02-17 16:41 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/patch/SignatureDetectionPatch.kt
> +@Description("Disable the signature detection.")
```suggestion
@Description("Disables detection of incorrect signature.")
```

2023-02-17 16:41 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/patch/SignatureDetectionPatch.kt
> +class SignatureDetectionPatch : BytecodePatch(
Please format the code.

2023-02-17 16:41 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/misc/unlockplus/patch/UnlockPlusPatch.kt
> +@Description("Unlock plus features.")
```suggestion
@Description("Unlocks plus features.")
```

2023-02-17 16:41 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/misc/unlockplus/patch/UnlockPlusPatch.kt
> +            ?: return PatchResultError("Can't find isPlusUnlocked method")
```suggestion
            ?: return IsPlusUnlockedFingerprint.toErrorResult()
```

2023-02-18 23:00 UTC, oSumAtrIX requested changes
Seems like you [overwrote](https://github.com/revanced/revanced-patches/compare/e264941bbfc4efe7d55addb5ff979ff643ef3df0..983c418c58877bd73f83170c11ef54e0cac33289) my [changes](https://github.com/revanced/revanced-patches/commit/983c418c58877bd73f83170c11ef54e0cac33289) with [your force push](https://github.com/revanced/revanced-patches/commit/983c418c58877bd73f83170c11ef54e0cac33289). 
Please revert your force-push via the reflog and merge or rebase your review suggestions on top of my changes, as they contain various fixes, your force-push has overwritten.

2023-02-18 23:00 UTC, oSumAtrIX commented on CHANGELOG.md
> +# [2.162.0-dev.6](https://github.com/revanced/revanced-patches/compare/v2.162.0-dev.5...v2.162.0-dev.6) (2023-02-18)
This file should not be committed, please remove it.

2023-02-18 23:00 UTC, oSumAtrIX commented on README.md
This file should not be committed, please remove it.

2023-02-18 23:00 UTC, oSumAtrIX commented on gradle.properties
>  kotlin.code.style = official
This file should not be committed, please remove it.

2023-02-18 23:00 UTC, oSumAtrIX commented on patches.json
> +[{"name":"always-autorepeat","description":"Always repeats the playing video again.","version":"0.0.1","excluded":false,"options":[],"dependencies":["integrations"],"compatiblePackages":[{"name":"com
This file should not be committed, please remove it.

2023-02-18 23:00 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/patch/ShowSeekbarPatch.kt
>  package app.revanced.patches.tiktok.interaction.seekbar.patch
Why is this in this commit? Your commits are messed up.

2023-02-21 00:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/patch/SignatureDetectionPatch.kt
> +            it.resolve(context,onCreateMethod!!,MainOnCreateFingerprint.result?.classDef!!)
Please format your code.

2023-02-21 00:49 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/patch/SignatureDetectionPatch.kt
> +@Patch
Is this meant to be a user-facing patch? It doesn't really serve any purpose in itself.

2023-02-21 00:50 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/patch/SignatureDetectionPatch.kt
> +        }
There is quite a lot going on here, especially with nullability and null assertions, might want to look into reducing noise here.

2023-02-22 05:27 UTC, oSumAtrIX commented
Pushed some refactoring changes, please test so we can merge.

2023-02-22 05:28 UTC, oSumAtrIX approved these changes

2023-02-22 11:02 UTC, nik2143 commented
Working, can be merged

2023-02-22 11:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/signature/patch/SignatureDetectionPatch.kt
> +        with(mainOnCreate.mutableMethod) {
```suggestion
        mainOnCreate.mutableMethod.apply {
```

2023-02-22 11:12 UTC, merged

2023-02-22 11:12 UTC, oSumAtrIX commented
Thanks