feat(relay): add change-client-id patch
ReVanced/revanced-patches-template pull request #2491
Opened 2023-06-25 02:14 UTC by gudmunduro

Add a patch to change client ID in `Relay for reddit`

closes: #2436

2023-06-25 02:17 UTC, oSumAtrIX requested changes

2023-06-25 02:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +class ChangeClientIdPatch :
Please format the class.

2023-06-25 02:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +@Description("Changes the OAuth client ID")
```suggestion
@Description("Changes the OAuth client ID.")
```

2023-06-25 02:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +@Compatibility([Package("free.reddit.news"), Package("reddit.news")])
It has two?

2023-06-25 02:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +class ChangeClientIdPatch :
Extend from `AbstractClientIdPatch`, follow the same style as the existing Reddit client patches.

2023-06-25 02:47 UTC, gudmunduro commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +@Compatibility([Package("free.reddit.news"), Package("reddit.news")])
Separate app for free and pro version

2023-06-25 02:53 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +@Description("Changes the OAuth client ID in Relay for Reddit.")
The user already knows which app they patch
```suggestion
@Description("Changes the OAuth client ID.")
```

2023-06-25 02:54 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +
```suggestion
```

2023-06-25 02:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeClientIdPatch.kt
> +        return PatchResultSuccess()
```suggestion
        val result = GetClientIdFingerprint.result?.mutableMethod?.replaceInstruction(0, "const-string v0, \"$clientId\"")
            ?: return GetClientIdFingerprint.toErrorResult()

        return PatchResultSuccess()
```

2023-06-25 03:03 UTC, oSumAtrIX approved these changes

2023-06-25 03:13 UTC, oSumAtrIX approved these changes

2023-06-25 03:13 UTC, merged

2023-06-25 17:34 UTC, Toiletmason commented
@gudmunduro Nice work my man. I would open this up to the pro version of the app. The free version is going to be dropped, while the pro version will continue to receive updates as far as I have heard.

2023-06-25 18:55 UTC, LisoUseInAIKyrios commented
I'm seeing this error while patching:
`java.lang.NoSuchMethodException: app.revanced.patches.reddit.customclients.ChangeOAuthClientIdPatchAnnotation.<init>()`

Reverting this merge fixes the error.  A fix is needed.

2023-06-25 19:02 UTC, oSumAtrIX commented
Is this a runtime error and what's the stack trace?

2023-06-25 19:08 UTC, LisoUseInAIKyrios commented
It's a patch error.

```
java.lang.NoSuchMethodException: app.revanced.patches.reddit.customclients.ChangeOAuthClientIdPatchAnnotation.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:318)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:42)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:356)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

```

2023-06-25 22:47 UTC, gudmunduro commented
> @gudmunduro Nice work my man. I would open this up to the pro version of the app. The free version is going to be dropped, while the pro version will continue to receive updates as far as I have heard.

This should also work for the pro version

2023-08-03 01:27 UTC, toadboi98 commented
> pro

I am having an issue patching the pro version (reddit.news.apk) which I downloaded from the playstore. Any suggestions? 

`SEVERE: Change OAuth client id failed: app.revanced.patcher.patch.PatchResultError: Failed to resolve LoginActivityClientIdFingerprint`

2023-08-03 01:27 UTC, oSumAtrIX commented
Open an issue.

2023-12-03 08:55 UTC, brian6932 commented
Sorry for the bump, but were you ever able to patch the Pro version (`reddit.news` not `free.reddit.news`)? @toadboi98
I can patch the normal APK just fine, but for some reason the Pro patch doesn't work for me, it patches without any errors, but doesn't seem to use the CID, and just says `Failed to load content` (both APKs are on version `10.2.40`)

Due to the lack of response, I'll open an issue regarding this