feat(music): add permanent repeat & shuffle toggle
ReVanced/revanced-patches-template pull request #2722
Opened 2023-08-02 05:20 UTC by MatthewCash

To resolve #1295 for YouTube Music this adds

- Permanent repeat toggle
- Permanent shuffle toggle
- Settings page for the toggles and import/export

I was able to reuse almost everything required for the settings page from the YouTube patches because the apps are similar. YT Music does not have the `Theme.YouTube.Settings.Dark` theme so I went with `Theme.YouTubeMusic`, it looks similar but [has the app's logo in the center of the screen](https://i.imgur.com/mCib1Df.png) for some reason.

Because the repeat/shuffle buttons are part of the layout, I put the permanent toggle patches in the `layout/` directory, but I am not sure if that is actually the best place for them.

2023-08-02 12:03 UTC, oSumAtrIX requested changes
This duplicates code quite a lot. Please abstract in a way that does not duplicate it. Also, a patch for settings should be added in another pull request. For the scope of this PR, adding the patch that enables the patches permanently suffices.

2023-08-02 12:07 UTC, oSumAtrIX commented
Please also separate this PR into two, introducing each patch.

2023-08-03 16:27 UTC, oSumAtrIX commented
> When the patch is enabled, the repeat button will stay enabled until it is manually disabled.

Isn't it okay to include the patch by default because you can enable or disable it?

2023-08-04 00:46 UTC, MatthewCash commented
> > When the patch is enabled, the repeat button will stay enabled until it is manually disabled.
> 
> Isn't it okay to include the patch by default because you can enable or disable it?

The default behavior is for repeat to be automatically disabled when a new song is selected. This patch prevents that behavior. I think it should be opt-in since some users may not prefer having to manually disable song repeating, but I don't think its a big deal either way.

2023-08-04 13:46 UTC, merged