feat: hide watch in vr
ReVanced/revanced-patches-template pull request #911
Opened 2022-10-30 06:16 UTC by inotia00

description
Hide the `Watch in VR` item from the menu items.

depend on
https://github.com/revanced/revanced-integrations/pull/191

screenshot
https://imgur.com/a/ddWBQYC

related issues page (`patch-request`)
https://github.com/revanced/revanced-patches/issues/790
※ If PR is merged, please close it.

Only the YouTube version that has been confirmed that the fingerprint is not broken has been added to the Compatibility.

2022-10-30 11:56 UTC, oSumAtrIX requested changes

2022-10-30 11:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/watchinvr/patch/WatchinVRPatch.kt
> +@Description("Hide the Watch in VR item from the menu item.")
```suggestion
@Description("Hides the "Watch in VR" context item from the player settings flyout panel.")
```

2022-10-30 12:00 UTC, oSumAtrIX requested changes

2022-10-30 12:00 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/watchinvr/patch/WatchinVRPatch.kt
> +                StringResource("revanced_hide_watch_in_vr_title", "Hide watch in vr"),
```suggestion
                StringResource("revanced_hide_watch_in_vr_title", "Hide Watch in VR option"),
```

2022-10-30 12:00 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/watchinvr/patch/WatchinVRPatch.kt
> +                StringResource("revanced_hide_watch_in_vr_summary_on", "Watch in vr item is hidden from menu item"),
```suggestion
                StringResource("revanced_hide_watch_in_vr_summary_on", "Watch in VR option is hidden"),
```

2022-10-30 12:00 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/watchinvr/patch/WatchinVRPatch.kt
> +                StringResource("revanced_hide_watch_in_vr_summary_off", "Watch in vr item is shown from menu item")
```suggestion
                StringResource("revanced_hide_watch_in_vr_summary_off", "Watch in VR option is shown")
```

2022-10-30 12:00 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/watchinvr/patch/WatchinVRPatch.kt
> +@Description("Hides the "Watch in VR" context item from the player settings flyout panel.")
```suggestion
@Description("Hides the Watch in VR option from the player settings flyout panel.")
```

2022-10-30 12:01 UTC, merged

2022-10-31 04:03 UTC, rohan2000github commented
Could you please make a similar patch for Hide "help and feedback" and hide "more from ____".